/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as CursoCanvaRouteImport } from './routes/curso-canva'
import { Route as CertificadoRouteImport } from './routes/certificado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuloModuleIdRouteImport } from './routes/modulo.$moduleId'
import { Route as ModuloModuleIdAulaLessonIdRouteImport } from './routes/modulo.$moduleId.aula.$lessonId'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoCanvaRoute = CursoCanvaRouteImport.update({
  id: '/curso-canva',
  path: '/curso-canva',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoRoute = CertificadoRouteImport.update({
  id: '/certificado',
  path: '/certificado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloModuleIdRoute = ModuloModuleIdRouteImport.update({
  id: '/modulo/$moduleId',
  path: '/modulo/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloModuleIdAulaLessonIdRoute =
  ModuloModuleIdAulaLessonIdRouteImport.update({
    id: '/aula/$lessonId',
    path: '/aula/$lessonId',
    getParentRoute: () => ModuloModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificado': typeof CertificadoRoute
  '/curso-canva': typeof CursoCanvaRoute
  '/materiais': typeof MateriaisRoute
  '/ranking': typeof RankingRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRouteWithChildren
  '/modulo/$moduleId/aula/$lessonId': typeof ModuloModuleIdAulaLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificado': typeof CertificadoRoute
  '/curso-canva': typeof CursoCanvaRoute
  '/materiais': typeof MateriaisRoute
  '/ranking': typeof RankingRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRouteWithChildren
  '/modulo/$moduleId/aula/$lessonId': typeof ModuloModuleIdAulaLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificado': typeof CertificadoRoute
  '/curso-canva': typeof CursoCanvaRoute
  '/materiais': typeof MateriaisRoute
  '/ranking': typeof RankingRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRouteWithChildren
  '/modulo/$moduleId/aula/$lessonId': typeof ModuloModuleIdAulaLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificado'
    | '/curso-canva'
    | '/materiais'
    | '/ranking'
    | '/modulo/$moduleId'
    | '/modulo/$moduleId/aula/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificado'
    | '/curso-canva'
    | '/materiais'
    | '/ranking'
    | '/modulo/$moduleId'
    | '/modulo/$moduleId/aula/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/certificado'
    | '/curso-canva'
    | '/materiais'
    | '/ranking'
    | '/modulo/$moduleId'
    | '/modulo/$moduleId/aula/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificadoRoute: typeof CertificadoRoute
  CursoCanvaRoute: typeof CursoCanvaRoute
  MateriaisRoute: typeof MateriaisRoute
  RankingRoute: typeof RankingRoute
  ModuloModuleIdRoute: typeof ModuloModuleIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso-canva': {
      id: '/curso-canva'
      path: '/curso-canva'
      fullPath: '/curso-canva'
      preLoaderRoute: typeof CursoCanvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado': {
      id: '/certificado'
      path: '/certificado'
      fullPath: '/certificado'
      preLoaderRoute: typeof CertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$moduleId': {
      id: '/modulo/$moduleId'
      path: '/modulo/$moduleId'
      fullPath: '/modulo/$moduleId'
      preLoaderRoute: typeof ModuloModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$moduleId/aula/$lessonId': {
      id: '/modulo/$moduleId/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/modulo/$moduleId/aula/$lessonId'
      preLoaderRoute: typeof ModuloModuleIdAulaLessonIdRouteImport
      parentRoute: typeof ModuloModuleIdRoute
    }
  }
}

interface ModuloModuleIdRouteChildren {
  ModuloModuleIdAulaLessonIdRoute: typeof ModuloModuleIdAulaLessonIdRoute
}

const ModuloModuleIdRouteChildren: ModuloModuleIdRouteChildren = {
  ModuloModuleIdAulaLessonIdRoute: ModuloModuleIdAulaLessonIdRoute,
}

const ModuloModuleIdRouteWithChildren = ModuloModuleIdRoute._addFileChildren(
  ModuloModuleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificadoRoute: CertificadoRoute,
  CursoCanvaRoute: CursoCanvaRoute,
  MateriaisRoute: MateriaisRoute,
  RankingRoute: RankingRoute,
  ModuloModuleIdRoute: ModuloModuleIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
