/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CertificadoRouteImport } from './routes/certificado'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ModuloModuleIdRouteImport } from './routes/modulo.$moduleId'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminModulosRouteImport } from './routes/admin.modulos'
import { Route as AdminCursosRouteImport } from './routes/admin.cursos'
import { Route as AdminAulasRouteImport } from './routes/admin.aulas'
import { Route as ModuloModuleIdAulaLessonIdRouteImport } from './routes/modulo.$moduleId.aula.$lessonId'

const CertificadoRoute = CertificadoRouteImport.update({
  id: '/certificado',
  path: '/certificado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ModuloModuleIdRoute = ModuloModuleIdRouteImport.update({
  id: '/modulo/$moduleId',
  path: '/modulo/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulosRoute = AdminModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAulasRoute = AdminAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AdminRoute,
} as any)
const ModuloModuleIdAulaLessonIdRoute =
  ModuloModuleIdAulaLessonIdRouteImport.update({
    id: '/aula/$lessonId',
    path: '/aula/$lessonId',
    getParentRoute: () => ModuloModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/certificado': typeof CertificadoRoute
  '/admin/aulas': typeof AdminAulasRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/modulo/$moduleId/aula/$lessonId': typeof ModuloModuleIdAulaLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certificado': typeof CertificadoRoute
  '/admin/aulas': typeof AdminAulasRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/modulo/$moduleId/aula/$lessonId': typeof ModuloModuleIdAulaLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/certificado': typeof CertificadoRoute
  '/admin/aulas': typeof AdminAulasRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/modulo/$moduleId/aula/$lessonId': typeof ModuloModuleIdAulaLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/certificado'
    | '/admin/aulas'
    | '/admin/cursos'
    | '/admin/modulos'
    | '/admin/usuarios'
    | '/modulo/$moduleId'
    | '/admin/'
    | '/modulo/$moduleId/aula/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/certificado'
    | '/admin/aulas'
    | '/admin/cursos'
    | '/admin/modulos'
    | '/admin/usuarios'
    | '/modulo/$moduleId'
    | '/admin'
    | '/modulo/$moduleId/aula/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/certificado'
    | '/admin/aulas'
    | '/admin/cursos'
    | '/admin/modulos'
    | '/admin/usuarios'
    | '/modulo/$moduleId'
    | '/admin/'
    | '/modulo/$moduleId/aula/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CertificadoRoute: typeof CertificadoRoute
  ModuloModuleIdRoute: typeof ModuloModuleIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/certificado': {
      id: '/certificado'
      path: '/certificado'
      fullPath: '/certificado'
      preLoaderRoute: typeof CertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/modulo/$moduleId': {
      id: '/modulo/$moduleId'
      path: '/modulo/$moduleId'
      fullPath: '/modulo/$moduleId'
      preLoaderRoute: typeof ModuloModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modulos': {
      id: '/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminModulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/aulas': {
      id: '/admin/aulas'
      path: '/aulas'
      fullPath: '/admin/aulas'
      preLoaderRoute: typeof AdminAulasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/modulo/$moduleId/aula/$lessonId': {
      id: '/modulo/$moduleId/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/modulo/$moduleId/aula/$lessonId'
      preLoaderRoute: typeof ModuloModuleIdAulaLessonIdRouteImport
      parentRoute: typeof ModuloModuleIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAulasRoute: typeof AdminAulasRoute
  AdminCursosRoute: typeof AdminCursosRoute
  AdminModulosRoute: typeof AdminModulosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAulasRoute: AdminAulasRoute,
  AdminCursosRoute: AdminCursosRoute,
  AdminModulosRoute: AdminModulosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ModuloModuleIdRouteChildren {
  ModuloModuleIdAulaLessonIdRoute: typeof ModuloModuleIdAulaLessonIdRoute
}

const ModuloModuleIdRouteChildren: ModuloModuleIdRouteChildren = {
  ModuloModuleIdAulaLessonIdRoute: ModuloModuleIdAulaLessonIdRoute,
}

const ModuloModuleIdRouteWithChildren = ModuloModuleIdRoute._addFileChildren(
  ModuloModuleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CertificadoRoute: CertificadoRoute,
  ModuloModuleIdRoute: ModuloModuleIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
